#ifndef PROTOCOLFORMATSRINGS_H
#define PROTOCOLFORMATSRINGS_H

#include <QString>

#include <map>

namespace ProtocolFormat {
enum class ProtocolStringLiteral {
    SEND_CHAT_MESSAGE_REQUEST_TYPE,
    GET_CHAT_HISTORY_REQUEST_TYPE,
    NOTIFICATION_REQUEST_TYPE,
    REQUEST_TYPE_KEY_NAME,
    CHAT_MESSAGE_KEY,
    CHAT_HISTORY_KEY_NAME,
    SEND_CHAT_MESSAGE_RESULT_KEY_NAME,
    SEND_CHAT_MESSAGE_RESULT_COMPLETED,
    SEND_CHAT_MESSAGE_RESULT_FAILED,
    NOTIFICATION_TYPE_KEY_NAME,
    NOTIFICATION_MESSAGES_UPDATED
};

QString getProtocolStringLiteral(const ProtocolStringLiteral key);
}

#endif // PROTOCOLFORMATSRINGS_H
